"""Local HIL-SERL learner boundary.

Heavy JAX/Flax modules stay lazily imported inside their public functions so
the robot-side actor and receive-server contract tests remain lightweight.
"""

from ur_env.learner.agent import (
    LearnerDependencyError,
    ResNetAssetError,
    create_hybrid_sac_agent,
    default_resnet_source,
    ensure_resnet10_cache,
    file_sha256,
    validate_learner_dependencies,
    verify_resnet10_asset,
)
from ur_env.learner.batches import (
    LearnerBatchError,
    RLPDBatchSampler,
    ReplayIngressView,
    SamplingMetrics,
    proportional_sample_counts,
    sample_proportional_counts,
    sanitize_learner_batch,
)
from ur_env.learner.checkpoint import (
    CheckpointCorruptError,
    CheckpointError,
    CheckpointExistsError,
    CheckpointFingerprintError,
    CheckpointLockError,
    CheckpointManager,
    CheckpointRunLock,
    CheckpointSpaceError,
    LearnerFingerprint,
    RestoredCheckpoint,
)
from ur_env.learner.emergency import (
    RescueResult,
    read_replay_snapshot_manifest,
    rescue_learner_state,
    save_replay_snapshot,
)
from ur_env.learner.config import (
    FROZEN_TRUNK_REPRESENTATION,
    FROZEN_TRUNK_SYNTHETIC_E2E_MODEL_REVISION,
    LEARNER_AUGMENTATION,
    LearnerConfig,
    RESNET10_SHA256,
)
from ur_env.learner.composition import (
    LearnerAssembly,
    LearnerCompositionError,
    LearnerWorker,
    LearnerWorkerStatus,
    PreparedLearnerState,
    build_actor_service,
    compose_learner,
    preflight_checkpoint_run,
    prepare_learner_state,
)
from ur_env.learner.demo import (
    CanonicalTransitionPool,
    DemoContractError,
    DemoSidecar,
    LoadedDemos,
    load_demo_object,
    load_demo_pickle,
    load_demo_pickles,
)
from ur_env.learner.fake_demo import (
    FAKE_DEMO_PICKLE_PROTOCOL,
    build_fake_demo_payload,
    write_fake_demo_pickle,
)
from ur_env.learner.recorded_demo import (
    ACTION_SOURCE as RECORDED_DEMO_ACTION_SOURCE,
    CONVERSION_REVISION as RECORDED_DEMO_CONVERSION_REVISION,
    ConvertedRecordedDemos,
    RecordedDemoConversionError,
    TakeConversionStats,
    convert_recorded_take,
    convert_recorded_takes,
    policy_action_from_command_poses,
    write_recorded_demo_pickle,
)
from ur_env.learner.feature_demo import (
    FeatureDemoContractError,
    FeatureDemoMemoryEstimate,
    FrozenTrunkDemoExtractor,
    FrozenTrunkFeatureDemoPool,
    convert_loaded_demos_to_feature_pool,
    estimate_feature_demo_memory,
)
from ur_env.learner.feature_replay import (
    DEFAULT_INTERVENTION_CAPACITY as DEFAULT_FEATURE_INTERVENTION_CAPACITY,
    DEFAULT_MEMORY_RESERVE_BYTES as DEFAULT_FEATURE_MEMORY_RESERVE_BYTES,
    DEFAULT_REPLAY_CAPACITY as DEFAULT_FEATURE_REPLAY_CAPACITY,
    FEATURE_AUGMENTATION,
    FEATURE_ENCODING_ID,
    FEATURE_KEYS,
    FEATURE_MAP_DTYPE,
    FEATURE_MAP_SHAPE,
    FeatureExtractionError,
    FeatureReplayError,
    FeatureReplayIngress,
    FeatureReplayMemoryError,
    FeatureReplayMemoryEstimate,
    FeatureTransitionRing,
    FrozenTrunkFeatureExtractor,
    estimate_feature_replay_memory,
    preflight_feature_replay_memory,
    system_available_memory_bytes,
)
from ur_env.learner.frozen_trunk import (
    FROZEN_TRUNK_CONTRACT,
    FROZEN_TRUNK_FEATURE_CONTRACT_REVISION,
    FROZEN_TRUNK_FEATURE_DTYPE,
    FROZEN_TRUNK_FEATURE_SHAPE,
    FROZEN_TRUNK_MODEL_REVISION,
    FROZEN_TRUNK_PARAMETER_PATH,
    FrozenResNet10TrunkExtractor,
    FrozenTrunkFeatureContract,
    FrozenTrunkFeatureSchemaError,
    create_frozen_trunk_feature_agent,
    validate_frozen_trunk_feature,
    validate_frozen_trunk_observation,
)
from ur_env.learner.logging import JsonlWandbLogger, LearnerLoggingError
from ur_env.learner.ingress import (
    FaultGatedReplayIngress,
    ReplayIngressFault,
    ReplayIngressFaultError,
)
from ur_env.learner.policy import (
    PolicyPublisher,
    PolicySnapshot,
    PolicyValidationError,
    VersionedPolicyRuntime,
    canonical_policy_observation,
    validate_parameter_tree,
    validate_tree_finite,
)
from ur_env.learner.runtime import (
    HILSERLLearner,
    LearnerFault,
    LearnerFaultError,
    LearnerNotReadyError,
    LearnerStepResult,
    LearnerWarmupResult,
)


__all__ = [
    "CanonicalTransitionPool",
    "CheckpointCorruptError",
    "CheckpointError",
    "CheckpointExistsError",
    "CheckpointFingerprintError",
    "CheckpointLockError",
    "CheckpointManager",
    "CheckpointRunLock",
    "CheckpointSpaceError",
    "RescueResult",
    "read_replay_snapshot_manifest",
    "rescue_learner_state",
    "save_replay_snapshot",
    "ConvertedRecordedDemos",
    "DemoContractError",
    "DemoSidecar",
    "FaultGatedReplayIngress",
    "FAKE_DEMO_PICKLE_PROTOCOL",
    "DEFAULT_FEATURE_INTERVENTION_CAPACITY",
    "DEFAULT_FEATURE_MEMORY_RESERVE_BYTES",
    "DEFAULT_FEATURE_REPLAY_CAPACITY",
    "FEATURE_AUGMENTATION",
    "FEATURE_ENCODING_ID",
    "FEATURE_KEYS",
    "FEATURE_MAP_DTYPE",
    "FEATURE_MAP_SHAPE",
    "FeatureDemoContractError",
    "FeatureDemoMemoryEstimate",
    "FeatureExtractionError",
    "FeatureReplayError",
    "FeatureReplayIngress",
    "FeatureReplayMemoryError",
    "FeatureReplayMemoryEstimate",
    "FeatureTransitionRing",
    "FrozenTrunkFeatureExtractor",
    "FROZEN_TRUNK_CONTRACT",
    "FROZEN_TRUNK_FEATURE_CONTRACT_REVISION",
    "FROZEN_TRUNK_FEATURE_DTYPE",
    "FROZEN_TRUNK_FEATURE_SHAPE",
    "FROZEN_TRUNK_MODEL_REVISION",
    "FROZEN_TRUNK_PARAMETER_PATH",
    "FROZEN_TRUNK_REPRESENTATION",
    "FROZEN_TRUNK_SYNTHETIC_E2E_MODEL_REVISION",
    "FrozenResNet10TrunkExtractor",
    "FrozenTrunkDemoExtractor",
    "FrozenTrunkFeatureDemoPool",
    "FrozenTrunkFeatureContract",
    "FrozenTrunkFeatureSchemaError",
    "HILSERLLearner",
    "JsonlWandbLogger",
    "LearnerBatchError",
    "LearnerAssembly",
    "LearnerCompositionError",
    "LearnerConfig",
    "LearnerDependencyError",
    "LearnerFault",
    "LearnerFaultError",
    "LearnerFingerprint",
    "LearnerLoggingError",
    "LEARNER_AUGMENTATION",
    "LearnerNotReadyError",
    "LearnerStepResult",
    "LearnerWarmupResult",
    "LearnerWorker",
    "LearnerWorkerStatus",
    "LoadedDemos",
    "PolicyPublisher",
    "PolicySnapshot",
    "PolicyValidationError",
    "PreparedLearnerState",
    "RECORDED_DEMO_ACTION_SOURCE",
    "RECORDED_DEMO_CONVERSION_REVISION",
    "RESNET10_SHA256",
    "RLPDBatchSampler",
    "ReplayIngressView",
    "ReplayIngressFault",
    "ReplayIngressFaultError",
    "RecordedDemoConversionError",
    "ResNetAssetError",
    "RestoredCheckpoint",
    "SamplingMetrics",
    "TakeConversionStats",
    "VersionedPolicyRuntime",
    "canonical_policy_observation",
    "build_actor_service",
    "build_fake_demo_payload",
    "compose_learner",
    "convert_loaded_demos_to_feature_pool",
    "convert_recorded_take",
    "convert_recorded_takes",
    "create_hybrid_sac_agent",
    "create_frozen_trunk_feature_agent",
    "default_resnet_source",
    "ensure_resnet10_cache",
    "estimate_feature_replay_memory",
    "estimate_feature_demo_memory",
    "file_sha256",
    "load_demo_object",
    "load_demo_pickle",
    "load_demo_pickles",
    "proportional_sample_counts",
    "preflight_checkpoint_run",
    "prepare_learner_state",
    "preflight_feature_replay_memory",
    "policy_action_from_command_poses",
    "sample_proportional_counts",
    "sanitize_learner_batch",
    "system_available_memory_bytes",
    "validate_learner_dependencies",
    "validate_frozen_trunk_feature",
    "validate_frozen_trunk_observation",
    "validate_parameter_tree",
    "validate_tree_finite",
    "verify_resnet10_asset",
    "write_fake_demo_pickle",
    "write_recorded_demo_pickle",
]
